name: CI_CD

#############################
# Start the job on all push #
#############################
on: workflow_dispatch
###############
# Set the Job #
###############
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./
          output_dir: ./out
          recurse: true
          front_page: README.md
          
      - uses: EndBug/add-and-commit@v9.1.1
        if: always()
        with: 
         add: ./out
        
