name: CI_CD

#############################
# Start the job on all push #
#############################
on: workflow_dispatch
###############
# Set the Job #
###############
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: codevise/documentation-js-action@v1
      with:
        input: ./
        output: ./docs

    # For example:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_PAT }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
          
